### ISSUE TITLE
ポイント計算のアルゴリズムを変更

### ISSUE THREAD

**Issue by hirotask** [Ringoame196/ZON-BATTLE2#8]
## 内容
この処理をif文を使わずに実装したい

https://github.com/Ringoame196/ZON-BATTLE2/blob/6de2aba9c4ae35df98bcbc2357d1881ca2fcf376/src/main/kotlin/com/github/Ringoame196/Item.kt#L99-L104

**Comment by Ringoame196** [comment]
https://github.com/Ringoame196/ZON-BATTLE2/commit/8878f4dad6e5eb654ba77ce4272f5e2dd37587a0

toIntOrNull\を使用し if文を使わずに元と同じ処理を実装
